ENT.Base 			= "npc_vj_creature_base"
ENT.Type 			= "ai"
ENT.PrintName 		= "Spider Queen"
ENT.Author 			= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "She's your mother!"
ENT.Instructions 	= "Click to spawn it."
ENT.Category		= "Dark Messiah"