ENT.Base 			= "npc_vj_creature_base"
ENT.Type 			= "ai"
ENT.PrintName 		= "Giant Worm"
ENT.Author 			= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Have Worm Sex."
ENT.Instructions 	= "Click on it to spawn it."
ENT.Category		= "Dark Messiah"